# Generated by Django 6.0.4 on 2026-05-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_favorite'),
        ('stores', '0003_alter_store_update_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_store_favorite',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(
                fields=('user', 'store'),
                name='unique_user_store_favorite'
            ),
        ),
    ]
