# Generated by Django 6.0.4 on 2026-05-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_favorite_unique_user_store_favorite_and_more'),
        ('stores', '0003_alter_store_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
