# Generated by Django 6.0.4 on 2026-05-05 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_user'),
        ('stores', '0003_alter_store_update_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='post',
                    name='store_id',
                ),
                migrations.AddField(
                    model_name='post',
                    name='store',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='stores.store'
                    ),
                ),
            ],
        ),
    ]
