# Generated by Django 6.0.4 on 2026-05-05 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_store_id_post_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostKidsMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('target_age', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_menus', to='posts.post')),
            ],
        ),
    ]
