# Generated by Django 6.0.4 on 2026-05-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_diaper_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='has_kids_chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='has_kids_cutlery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='has_kids_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_stroller_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PostSeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='posts.post')),
            ],
        ),
    ]
