# Generated by Django 6.0.4 on 2026-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_has_diaper_table_post_has_kids_chair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postseattype',
            name='seat_type',
            field=models.IntegerField(choices=[(1, '座敷'), (2, 'テーブル'), (3, '個室')], default=1),
            preserve_default=False,
        ),
    ]
