# Generated by Django 6.0.4 on 2026-05-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postseattype_seat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='facilities',
        ),
    ]
