# Generated by Django 6.0.4 on 2026-05-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('holiday', models.CharField(blank=True, max_length=100)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('parking', models.CharField(blank=True, max_length=255)),
                ('target_age', models.CharField(blank=True, max_length=50)),
                ('has_kids_chair', models.BooleanField(default=False)),
                ('is_stroller_ok', models.BooleanField(default=False)),
                ('has_diapper', models.BooleanField(default=False)),
                ('has_kids_space', models.BooleanField(default=False)),
                ('has_kids_cutlery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
