# Generated by Django 6.0.4 on 2026-05-02 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='has_diapper',
        ),
        migrations.RemoveField(
            model_name='store',
            name='has_kids_chair',
        ),
        migrations.RemoveField(
            model_name='store',
            name='has_kids_cutlery',
        ),
        migrations.RemoveField(
            model_name='store',
            name='has_kids_space',
        ),
        migrations.RemoveField(
            model_name='store',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='store',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_stroller_ok',
        ),
        migrations.RemoveField(
            model_name='store',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='store',
            name='target_age',
        ),
        migrations.AddField(
            model_name='store',
            name='business_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='parking_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='regular_holiday',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
