# Generated by Django 6.0.4 on 2026-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_has_diapper_remove_store_has_kids_chair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
