# Generated by Django 6.0.4 on 2026-05-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
